server:
  port: 8087
spring:
  application:
    name: Metrics Producer
  kafka:
    bootstrap-servers: localhost:9092
    my-topic: metrics-topic
  security:
    user:
      name: producer
      password: producer