server:
  port: 8088
spring:
  application:
    name: KafkaConsumer
  kafka:
    bootstrap-servers: localhost:29092
    my-topic: metrics-topic

  datasource:
    url: jdbc:postgresql://localhost:5446/hw2?currentSchema=hw2
    username: sumkin
    password: hw224032024
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: hw2
        format_sql: true
        type: trace
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true
    default-schema: liquibase

  preliquibase:
    enabled: true